name: Deploy App Messages

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4 

            -
                name: Login ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2
                with:
                    registry: us-east-1.amazonaws.com
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1   
            - 
                name: Build Docker image
                run: docker build -t app-messages:latest .
            -
                name: Tag Docker Image
                run: docker tag app-messages:latest ${{ secrets.ECR_REPOSITORY }}:1.0
    
            -
                name: Push Docker Image to ECR
                run: docker push ${{ secrets.ECR_REPOSITORY }}:1.0   
            -
                name: Connect to EC2
                uses: appleboy/ssh-action@master  
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    port: ${{ secrets.EC2_SSH_PORT }}
                    script: |
                      docker pull ${{ secrets.ECR_REPOSITORY }}:1.0
                      docker stop messages || true
                      docker rm messages || true
                      docker run -d --name messages -p 3000:3000 
                      -e DB_URL=${{ secrets.DB_URL }} -e API_KEY=${{ secrets.API_KEY }} 
                      -e URL=${{ secrets.EC2_HOST }}
                      ${{ secrets.ECR_REPOSITORY }}:1.0   




                