name: Deploy App Simple Chat

on: 
    push:
        branches: [main]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4  
            -
                name: Log in to Docker Hub
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    username: ${{ secrets.USERNAME_DOCKERHUB }}
                    password: ${{ secrets.PASSWORD_DOCKERHUB }}    
            - 
                name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
                with:
                    images: talitaambrozio/app-messages 
            - 
                name: Build Docker image
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: "talitaambrozio/app-messages:1.0"
                    context: . 
    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push-image
        steps:        
            -               
                name: Connect to EC2
                uses: appleboy/ssh-action@master  
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    port: 22
                    script: |
                        docker stop messages || true
                        docker rm messages || true
                        docker pull talitaambrozio/app-messages:1.0
                        docker run --name messages -d -e DB_URL=${{ secrets.DB_URL }} -e API_KEY=${{ secrets.API_KEY }} -e URL=${{ secrets.EC2_HOST }} -p 3000:3000 talitaambrozio/app-messages:1.0             