name: Deploy App Messages

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4 
            - 
                name: Checkout repo
                uses: actions/checkout@v4 

   
            -
                name: Login to Docker Hub
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    username: ${{ secrets.USERNAME_DOCKERHUB }}
                    password: ${{ secrets.PASSWORD_DOCKERHUB }}         
            - 
                name: Build Docker image
                run: docker build -t app-messages:latest .
            -
                name: Tag Docker Image
                run: docker tag app-messages:latest talitaambrozio/app-messages:1.0
    
            -
                name: Push Docker Image to Docker Hub
                run: docker push talitaambrozio/app-messages:1.0   
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:            
            -
                name: Connect to EC2
                uses: appleboy/ssh-action@master  
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    port: 22
                    script: |
                      docker pull talitaambrozio/app-messages:1.0
                      docker stop messages || true
                      docker rm messages || true
                      docker run --name messages -d -e DB_URL=${{ secrets.DB_URL }} -e API_KEY=${{ secrets.API_KEY }} -e URL=${{ secrets.EC2_HOST }} -p 3000:3000 talitaambrozio/app-messages:1.0


                