name: Deploy App Simple Chat

on: 
    push:
        branches: [main]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4  
            -
                name: Log in to Docker Hub
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    username: ${{ secrets.USERNAME_DOCKERHUB }}
                    password: ${{ secrets.PASSWORD_DOCKERHUB }}         
            - 
                name: Build Docker image
                run: docker build -t app-messages:latest .
            - 
                name: Pull Docker image to get latest tag
                run: |
                  LAST_TAG=$(docker pull talitaambrozio/app-messages | grep -oP '(?<=1\.)\d+\.\d+')
                  if [ -z "$LAST_TAG" ]; then
                    NEXT_TAG="0.1"
                  else
                    NEXT_TAG=$(awk "BEGIN {print $LAST_TAG + 0.1}")
                  fi
            -
                name: Tag Docker Image
                run: docker tag app-messages:latest talitaambrozio/app-messages:$NEXT_TAG
    
            -
                name: Push Docker Image to Docker Hub
                run: docker push talitaambrozio/app-messages:$NEXT_TAG 
            -
                name: Connect to EC2
                uses: appleboy/ssh-action@master  
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    port: 22
                    script: |
                      docker pull talitaambrozio/app-messages:$NEXT_TAG
                      docker stop messages || true
                      docker rm messages || true
                      docker run --name messages -d -e DB_URL=${{ secrets.DB_URL }} -e API_KEY=${{ secrets.API_KEY }} -e URL=${{ secrets.EC2_HOST }} -p 3000:3000 talitaambrozio/app-messages:$NEXT_TAG


                