name: Deploy App Simple Chat

on: 
    push:
        branches: [main]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v4  
            -
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: talitaambrozio/app-messages 
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}

            -
                name: Log in to Docker Hub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.USERNAME_DOCKERHUB }}
                    password: ${{ secrets.PASSWORD_DOCKERHUB }}    
            - 
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push-image
        steps:        
            -               
                name: Connect to EC2
                uses: appleboy/ssh-action@master  
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    port: 22
                    script: |

                      
                        current_version=$(echo "${{ steps.meta.outputs.tags }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

                        docker stop talitaambrozio/app-messages:$current_version || true

                        new_version=$(semver bump patch $current_version)

                        docker pull talitaambrozio/app-messages:${{ steps.meta.outputs.tags }}

                        docker tag talitaambrozio/app-messages:${{ steps.meta.outputs.tags }} talitaambrozio/app-messages:$new_version

                        docker run --name messages -d -e DB_URL=${{ secrets.DB_URL }} -e API_KEY=${{ secrets.API_KEY }} -e URL=${{ secrets.EC2_HOST }} -p 3000:3000 talitaambrozio/app-messages:$new_version